### ISSUE TITLE
[Epic: js-waku] Reliability Protocol for Resource-Restricted Clients

### ISSUE THREAD

**Issue by chair28980** [logos-messaging/logos-delivery-js#2154]
### Our user story: 
1. As a developer, I want a simple API to register hooks to process messages on one or several content topics: https://github.com/waku-org/js-waku/pull/2092
2. As a developer, I do not care about shards or pubsub topics, I am only using autosharding
3. As developer, I want fair reliability when receiving messages (e..g redundant filter nodes + filter ping + store sync)
4. As a developer, I do not want the same incoming message to be processed several times (e.g. filter redundancy should be abstracted)
5. As a developer, I want fair reliability when sending messages.

#### Store

- [x] implement `store-v3`: https://github.com/waku-org/js-waku/pull/2036

#### Combination

- [x] Message verification and retry: https://github.com/waku-org/js-waku/issues/2075
- [x] Message retry for LightPush: https://github.com/waku-org/js-waku/issues/2069
- [x] Continuous discovery: https://github.com/waku-org/js-waku/issues/2051

#### Liveness of a node:

- [x] Node health state - https://github.com/waku-org/js-waku/issues/2070
- [x] Filter subscription recovery after offline state https://github.com/waku-org/js-waku/issues/2024
- [ ] (questionable) node recovery strategies https://github.com/waku-org/js-waku/issues/2076

#### Testing

- [ ] unit testing: https://github.com/waku-org/js-waku/issues/2078 and https://github.com/waku-org/js-waku/issues/2077
- [ ] Test pipeline - https://github.com/waku-org/js-waku/issues/2007

#### Filter: 

- [x] ensure number of peers to subscribe to is configurable, documented and respected by implementation; https://github.com/waku-org/js-waku/pull/2182/commits/02976823def29127a0238d425d5912aae94df195
- [x] dynamic peer management: https://github.com/waku-org/js-waku/issues/2002
    - [x] if filter ping fails on node 1 but not node 2, disconnect from node 1 and replace: https://github.com/waku-org/js-waku/pull/2052
    - [x] introduce a monitor if no messages are coming from peer A but are coming from peer B - drop A: https://github.com/waku-org/js-waku/pull/2057
- [x] automatically connect and subscribe to 2-3 filter nodes: https://github.com/waku-org/js-waku/issues/1463;
- [x] seen cache to ensure dupe messages are not bubbled up;
- [x] when subscribicing, starting running filter ping: https://github.com/waku-org/js-waku/issues/1995;
- [x] keep alive feature https://github.com/waku-org/js-waku/pull/1970
- [x] filter pings should work per peer, instead of per subscription

#### LightPush: 

- [x] ensure number of peers to use is configurable and documented https://github.com/waku-org/js-waku/pull/2182/commits/02976823def29127a0238d425d5912aae94df195
- [x] dynamic peer management: https://github.com/waku-org/js-waku/issues/2002
  - [x] if any node from the pool rejects messages - replace it;
- [x] connect to 2/3 lightpush node when sending messages;

------

<details>
<summary>First revision</summary>

## Tasks (obsolete) 
- [ ] write interop tests to cover `non-relay client` user stories;
- [x] protocol reliability + exposing additional configs to enable / disable behavior + unit tests:
  - [x] Filter/LightPush uses more than one peer: https://github.com/waku-org/js-waku/issues/1463
- [x] orient protocols to be more RFC oriented + unit tests: https://github.com/waku-org/js-waku/issues/1886
  - [x] Filter: https://github.com/waku-org/js-waku/pull/1964
  - [x] LightPush: https://github.com/waku-org/js-waku/pull/1887
  - [x] Store: https://github.com/waku-org/js-waku/pull/1913

We can de-scope some of these streams in the interest of time.

</details>

<details>
<summary>Second revision</summary>

#### Filter: 

- [ ] ensure number of peers to subscribe to is configurable, documented and respected by implementation;
- [ ] Filter subscription recovery after offline state https://github.com/waku-org/js-waku/issues/2024

#### LightPush: 

- [ ] ensure number of peers to use is 
   - [x] configurable
   - [ ] documented

#### Store

- [ ] implement `store-v3`: https://github.com/waku-org/js-waku/pull/2036
- [ ] peer renewal for store peers;

#### Liveness of a node:

- [x] https://github.com/waku-org/js-waku/issues/2070
- [ ] 

#### Testing

- [ ] unit testing;
- [x] https://github.com/waku-org/js-waku/issues/2007

</details>
